version: '3'
services:

  # The Database
  database:
    image: postgres:10-alpine
#    volumes:
#      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chat_app
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret

  service-api:
    build:
      context: .
      dockerfile: ./bin/service-api.dockerfile
    ports:
    - 8000:8100
    volumes:
    - ./chat:/opt/application/chat
#    env_file:
#    - docker-compose.env
    environment:
      APP_GUNICORN_USE: chat.app:app
      APP_MIGRATE: 1
      APP_SECRET_KEY: qw93f846t5nbgvqfu4b3rnf
      POSTGRES_HOST: database

  frontend:
    build:
      context: .
      dockerfile: ./bin/frontend.dockerfile
    ports:
    - 8000:8000
    volumes:
    - ./frontend:/opt/application